### ISSUE TITLE
[INFO] IPFS Catcher mention vis-a-vis IPFS redirect userscript & Tampermonkey

### ISSUE THREAD

**Issue by JayBrown** [NeoTeo/ipfs-catcher#1]
fyi: https://github.com/Tampermonkey/tampermonkey/issues/393

**Comment by NeoTeo** [comment]
Not dead, just resting.

**Comment by JayBrown** [comment]
Handling multiple hashes and other elements in an IPFS address might be done by using `?(Qm.+)` instead of `?(Qm\w{44})` in [line 6](https://github.com/NeoTeo/ipfs-catcher/blob/master/ipfs-catcher.safariextension/startscript.js#L6). I'm currently testing it in my own redirect script for Tampermonkey, and it works fine.
